# Generated by Django 3.2.8 on 2021-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCryptoPrice',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_price', models.FloatField()),
                ('pair_name', models.CharField(help_text='from and to currency pairs which help identity the quotes should be : seprate example BTC:USD ', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
